[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[lib]
name = "raytracer"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
glam = { version = "0.30.9", features = ["fast-math"] }
rand = "0.9.2"
rayon = "1.11.0"
